--- #YAML:1.0
name:               MRS-Client
version:            0.52
abstract:           A SOAP-based client accessing MRS databases
author:
    - Martin Senger <martin.senger@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       0
    Math::BigInt:         0
    Test::More:           0
    XML::Compile::SOAP11:  0
    XML::Compile::Transport::SOAPHTTP:  0
    XML::Compile::WSDL11:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
